baseurl = "https://samfprogramming.netlify.com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  title = "CPH codes"
  subtitle = "CPH codes is a society that applies coding to address issues of the 21st century"
  author = "Jakob Jul Elben"
  github = "https://github.com/orgs/samfprogramming/"
  paginatePath = "blog"
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "dark"
  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"

  
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 20
  
[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 40
  
  