baseurl = "/"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  title = "CPH codes"
  author = "Jakob Jul Elben"
  
[[menu.main]]
  name = "Intro"
  url = "/intro"
  
[[menu.main]]
  name = "Hello"
  url = "/hello"