baseurl = "https://samfprogramming.netlify.com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  title = "CPH codes"
  author = "Jakob Jul Elben"
  github = "https://github.com/orgs/samfprogramming/"
  
[[menu.main]]
  name = "Intro"
  url = "/page/intro"
  weight = 10
  
[[menu.main]]
  name = "About"
  url = "/page/about"
  weight = 20
  
[[menu.main]]
  name = "Contact"
  url = "/page/about"
  weight = 20
  
[[menu.main]]
  name = "Blog"
  url = "/page/about"
  weight = 20